### ISSUE TITLE
Chez Hermes tag wrong

### ISSUE THREAD

**Issue by actordc** [vektorious/FM4_dl#3]
The correct tag for the show "Chez Hermes" seems to be 4CZTue, as the show is scheduled on Tuesdays. Current Tag in fm4.py is not working

**Comment by vektorious** [comment]
Hey @actordc, thanks for the submitting the issue. 
Since you already provide a solution, do you want to fix it yourself and submit a pull request?

**Comment by vektorious** [comment]
Thanks @actordc !
